from typing import Protocol, List, Optional
from uuid import UUID
from datetime import datetime
from app.schemas.user import UserOut, UserCreate
from app.schemas.group import GroupCreate, GroupOut, GroupUpdate
from app.schemas.event import EventCreate, EventOut, EventUpdate

class UserRepo(Protocol):
    async def create(self, data: UserCreate) -> UserOut: ...
    async def get_by_username(self, username: str) -> Optional[UserOut]: ...
    async def get_by_email(self, email: str) -> Optional[UserOut]: ...

class GroupRepo(Protocol):
    async def create(self, data: GroupCreate) -> GroupOut: ...
    async def list(self, q: Optional[str], category: Optional[str], limit: int, offset: int) -> List[GroupOut]: ...
    async def get(self, group_id: UUID) -> Optional[GroupOut]: ...
    async def update(self, group_id: UUID, data: GroupUpdate) -> Optional[GroupOut]: ...
    async def delete(self, group_id: UUID) -> bool: ...

class EventRepo(Protocol):
    async def create(self, data: EventCreate) -> EventOut: ...
    async def list(
        self,
        q: Optional[str],
        group_id: Optional[UUID],
        category: Optional[str],
        date_from: Optional[datetime],
        date_to: Optional[datetime],
        upcoming: bool,
        limit: int,
        offset: int,
    ) -> List[EventOut]: ...
    async def get(self, event_id: UUID) -> Optional[EventOut]: ...
    async def update(self, event_id: UUID, data: EventUpdate) -> Optional[EventOut]: ...
    async def delete(self, event_id: UUID) -> bool: ...
